## Ejercicio 1
* Crear una lista "asignaturas" con textos "matematicas","fisica","historia"
* Crear una lista "notas" con valores 9,9,8
* Crear una serie con la lista "notas" como valores, y la lista "Asignaturas" como indeices
* Crear la variable "nota_fisica" con la nota de la asignatura de "fisica"
* Mediante el metodo print muestre "la nota de fisica es"

In [1]:
import pandas as pd
import numpy as np

In [3]:
asignaturas = ["matematicas","fisica","historia"]
asignaturas

['matematicas', 'fisica', 'historia']

In [4]:
notas = [9,9,8]
notas

[9, 9, 8]

In [5]:
serie = pd.Series(data=notas, index=asignaturas)
serie

matematicas    9
fisica         9
historia       8
dtype: int64

In [6]:
nota_fisica = serie['fisica']
nota_fisica

9

In [7]:
print("La nota de fisica es un {}".format(nota_fisica))

La nota de fisica es un 9


## Ejercicio 2
El objetivo será crear un dataframe con las ventas de nuestras 3 oficinas para los meses de enero, febrero y marzo
* Crear una variable "ventas_enero" que contenga una lista de números enteros aleatorios entre 100 y 500
* Crear una variable "ventas_febrero" que contenga una lista de números enteros aleatorios entre 100 y 500
* Crear una variable "ventas_marzo" que contenga una lista de números enteros aleatorios entre 100 y 500
* Crear una variable "filas" que contenga esta lista de palabras: 'ventas_enero', 'ventas_febrero', 'ventas_marzo'
* Crear una variable "columnas" que contenga esta lista de palabras: 'oficina1', 'oficina2', 'oficina3'
* Crear una variable "ventas" que contenga una lista con los valores de ventas de enero, febrero y marzo
* Crear una variable "dataframne" que contenga las ventas, filas y columnas
mediante "print" muestre el valor de "Las ventas de enero para la oficina 1 son de ..."

In [9]:
ventas_enero = np.random.randint(100,500,3)
ventas_enero

array([439, 148, 449])

In [10]:
ventas_febrero = np.random.randint(100,500,3)
ventas_febrero

array([163, 236, 232])

In [11]:
ventas_marzo = np.random.randint(100,500,3)
ventas_marzo

array([250, 368, 242])

In [12]:
filas = ['ventas_enero', 'ventas_febrero', 'ventas_marzo']
filas

['ventas_enero', 'ventas_febrero', 'ventas_marzo']

In [13]:
columnas = ['oficina1', 'oficina2', 'oficina3']
columnas

['oficina1', 'oficina2', 'oficina3']

In [14]:
ventas = [ventas_enero, ventas_febrero, ventas_marzo]
ventas

[array([439, 148, 449]), array([163, 236, 232]), array([250, 368, 242])]

In [15]:
# data, filas, columnas
dataframne = pd.DataFrame(ventas, filas, columnas)
dataframne

oficina1  oficina2  oficina3
ventas_enero         439       148       449
ventas_febrero       163       236       232
ventas_marzo         250       368       242

In [ ]:
print('')