## Numpy arrays  - arange, zeros, ones, linspace, eye

In [1]:
import numpy as np

In [2]:
lista = [1,2,3,4]

In [3]:
array = np.array(lista)

In [4]:
array

array([1, 2, 3, 4])

In [5]:
lista2 = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
lista2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
array2 = np.array(lista2)
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
array = np.arange(5)
array

array([0, 1, 2, 3, 4])

In [9]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [11]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.linspace(3,9,20)

array([3.        , 3.31578947, 3.63157895, 3.94736842, 4.26315789,
       4.57894737, 4.89473684, 5.21052632, 5.52631579, 5.84210526,
       6.15789474, 6.47368421, 6.78947368, 7.10526316, 7.42105263,
       7.73684211, 8.05263158, 8.36842105, 8.68421053, 9.        ])

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Numpy arrays - números aleatorios - rand, randn, randint

In [15]:
np.random.rand(5)

array([0.31438424, 0.54742875, 0.98838218, 0.70142687, 0.75560896])

In [16]:
np.random.rand(3,3)

array([[0.37842895, 0.76609389, 0.34540836],
       [0.08117573, 0.03554443, 0.19370138],
       [0.52346121, 0.7705687 , 0.159524  ]])

In [17]:
np.random.randn(4)

array([ 0.48689023,  1.32968712,  0.59303398, -0.65495148])

In [18]:
np.random.randint(1,20)

17

In [19]:
np.random.randint(1,20, 5)

array([12, 12, 14, 15, 15])

## Numpy arrays - reshape

In [20]:
array = np.random.randint(1,100,25)

In [21]:
array

array([61, 92, 80, 42, 41, 92, 59,  6, 40, 91, 77, 67, 22, 78, 38, 22, 38,
       83, 62, 74,  1, 89, 84, 39, 94])

In [22]:
matriz = array.reshape(5,5)
matriz

array([[61, 92, 80, 42, 41],
       [92, 59,  6, 40, 91],
       [77, 67, 22, 78, 38],
       [22, 38, 83, 62, 74],
       [ 1, 89, 84, 39, 94]])

## Valor maximo y minimo

In [23]:
array = np.random.randint(1,100,50)
array

array([69, 15,  5, 52, 90, 96, 64, 56, 68, 53, 14, 18, 29,  6, 17, 29, 24,
        9, 66, 35, 58, 91,  2, 81, 62, 75, 75, 84, 23, 26, 91, 56, 42, 37,
       99, 56, 80,  4, 50, 72, 25, 10, 21, 36, 75, 59, 89, 46, 80, 96])

In [24]:
valor_maximo = array.max()
valor_maximo

99

In [25]:
posicion_valor_maximo = array.argmax()
posicion_valor_maximo

34

In [26]:
valor_minimo = array.min()
valor_minimo

2

In [27]:
posicion_valor_minimo = array.argmin()
posicion_valor_minimo

22

## Indexación de Array

In [28]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
array[0]

0

In [30]:
array[-1]

9

In [31]:
array[6:8]

array([6, 7])

In [32]:
array[6:]

array([6, 7, 8, 9])

In [33]:
array[:6]

array([0, 1, 2, 3, 4, 5])

In [34]:
array2 = array.copy()
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Seleccionar elementos de un array según una condición

In [35]:
condicion = array > 5
condicion

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [36]:
array6 = array[condicion]
array6

array([6, 7, 8, 9])

In [37]:
array[array % 2 == 0]

array([0, 2, 4, 6, 8])

## Operaciones sobre los arrays

In [38]:
array = np.arange(0, 10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
array + array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [40]:
array + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [41]:
np.max(array)

9

In [42]:
np.min(array)

0

## Ejercicio 1

* Crear una lista de número secuenciales con el valor mínimo de 10 y el valor maximo 39 
* Convierte esta lista en un lista o matriz de 2 dimenciones (3 filas por 10 columnas)
* Muestra por pantalla el valor del elemento de la esquina superior derecha de la matriz

In [44]:
lista = np.arange(10, 40)
lista

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [46]:
lista = lista.reshape(3, 10)
lista

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [48]:
lista[0][9]

19

## Ejericio 2

* Crear una lista de una dimensión con 9 valores aleatorios entre 0 y 100
* Convierte esta lista en un lista o matriz de 2 dimenciones (3 filas y 3 columnas)
* Muestra por pantalla el valor del elemento de la esquina inferior derecha de la matriz

In [49]:
lista2 = np.random.randint(0, 100, 9)

In [50]:
lista2

array([90, 58, 29, 72, 45, 15, 65, 85, 24])